---
title: Digidem Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  project:
    title: Project
    output: true
  uploads:
    title: Uploads
    output: true
email: petter@p-jo.se
description: Digidem Lab skapar framtidens processer för demokratiskt deltagande.
  Vi sätter nya verktyg för kollektiv intelligens i dina händer.
baseurl: ''
url: ''
author: Digidem Lab
twitter_username: digidemlab
github_username: p-jo
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components
theme: minima
sass:
  sass_dir: _sass
