---
title: Digidem Lab
timezone: UTC
collections:
  crew:
    title: Crew
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: projects
  values:
    layout: page
    lang: sv
    contact: true
- scope:
    path: ''
    type: posts
  values:
    layout: project
    lang: sv
- scope:
    path: ''
    type: crew
  values:
    lang: sv
permalink: "/:title/"
email: admin@digidemlab.org
baseurl: 
url: https://digidemlab.org
author: Digidem Lab
twitter:
  username: digidemlab
facebook:
  publisher: digidemlab
logo: "/assets/logotyp.png"
social:
  links:
  - https://twitter.com/digidemlab
  - https://www.facebook.com/digidemlab
  - https://www.instagram.com/digidemlab/
  - https://github.com/digidemlab
github_username: p-jo
repository: digidemlab/digidemlab.github.io
plugins:
- jemoji
- jekyll-seo-tag
t:
  sv:
    mission: Digidem Lab erbjuder tjänster och utvecklar metoder och verktyg för framtidens
      deltagande demokrati.
    language: Svenska
    member:
    - title: Styrelsemedlem i Global Participatory Budgeting Hub.
      image: "/assets/images/logo-pbp.png"
      url: https://www.participatorybudgeting.org/globalpbhub/
    - title: Styrelsemedlem och medgrundare till internationella Consul Democracy
        Foundation.
      image: "/assets/images/logo-consul.png"
      url: https://consulproject.org
    - title: Utveckling av medborgardialog i Göteborg och Stockholm med stöd av Vinnova.
      image: "/assets/images/logo-vinnova.png"
      url: https://www.vinnova.se/
    project-link: Läs mer om uppdraget
    more-projects: Fler uppdrag
    more-services: Läs mer om våra tjänster
    news: Nyheter
    more-news: Fler nyheter
    read-more: Läs mer
    contact-title: Vill du veta mer?
    contact-text: Kontakta oss för att diskutera gemensamma projekt eller få ett prisförslag
      på våra tjänster.
  en:
    mission: Digidem Lab offers services and develops platforms for the participatory
      democracy of the future.
    language: English
    member:
    - title: Board member of Global Participatory Budgeting Hub.
      image: "/assets/images/logo-pbp.png"
      url: https://www.participatorybudgeting.org/globalpbhub/
    - title: Co-founder and board member of Consul Democracy Foundation.
      image: "/assets/images/logo-consul.png"
      url: https://consulproject.org
    - title: Developing new methods for citizen participation with the support of
        Vinnova.
      image: "/assets/images/logo-vinnova.png"
      url: https://www.vinnova.se/en/
    project-link: Read about the project
    more-projects: More projects
    more-services: Read more about our services
    news: News
    more-news: More news
    read-more: Read more
    contact-title: Get in touch!
    contact-text: Get in touch to discuss ideas for projects or cooperation.
