---
title: Digidem Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: petter@p-jo.se
description: promoting digital tools for radical democracy
baseurl: ''
author: Digidem Lab
twitter_username: digidemlab
github_username: p-jo
markdown: kramdown
permalink: pretty
jekyll_get:
- data: projects
  json: https://secure.are.na/v2/channels/digidem-tools-web
  cache: true
prose:
  rooturl: _posts
exclude:
- ".sass-cache"
- bower_components
