---
title: Digidem Lab
timezone: UTC
collections:
  crew:
    title: Crew
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: posts
  values:
    layout: project
    lang: sv
- scope:
    path: ''
    type: crew
  values:
    lang: sv
permalink: "/projects/:title/"
email: admin@digidemlab.org
contact:
  sv:
    title: Prata med oss!
    text: Digidem Lab är ett oberoende och icke vinstdrivande labb för deltagande
      demokrati. [Läs mer om](/contact) hur vi kan hjälpa er organisation att hitta
      nya sätt att engagera och skapa processer för deltagande.
  en:
    title: Get in touch!
    text: Digidem Lab is a non-profit organisation promoting participatory democracy
      on all levels of society. Get in touch to see how we can help your movement
      or organisation to find new processes and tools for participation.
partner-text:
  sv: Digidem Lab arrangeras med hjälp av Allmänna Arvsfonden och ABF Göteborg i samarbete
    med Sveriges Kommuner och Landsting, Miljöpartiet de Gröna, LSU - Sveriges ungdomsorganisationer,
    Ung Media och Unga Rörelsehindrade Göteborgsklubben.
  en: Digidem Open Lab is co-organised with ABF Göteborg, with the support of Allmänna
    Arsvfonden and the cooperation of Sweden's Municipalities, The Swedish Green Party,
    The National Council of Swedish Youth Organisations (LSU), Young Media and Unga
    Rörelsehindrade Gothenburg.
partner-links:
- name: ABF
  logo: "/uploads/logotyp-abf.png"
  link: http://www.abf.se/goteborg
- name: Allmänna Arvsfonden
  logo: "/uploads/logotyp-arvsfonden.png"
  link: http://www.arvsfonden.se/
questions:
  sv: Projektledare
  en: Project manager
project-title:
  sv: Projekt
  en: Projects
project-link:
  sv: Alla projekt
  en: More projects
baseurl:
url: https://digidemlab.org
author: Digidem Lab
twitter:
  username: digidemlab
facebook:
  publisher: digidemlab
logo: "/assets/logotyp.png"
social:
  links:
  - https://twitter.com/digidemlab
  - https://www.facebook.com/digidemlab
  - https://www.instagram.com/digidemlab/
  - https://github.com/digidemlab
github_username: p-jo
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components
- path
theme: minima
sass:
  sass_dir: _sass
gems:
- jemoji
- jekyll-seo-tag
- jekyll-redirect-from
