title: Digidem Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: petter@p-jo.se
description: Digidem Lab skapar framtidens processer för demokratiskt deltagande. Vi sätter nya verktyg för kollektiv intelligens i dina händer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Digidem Lab
twitter_username: digidemlab
github_username: p-jo
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components

# Build settings
theme: minima
gems: [bootstrap, autoprefixer-rails, jekyll-assets]
sass:
    sass_dir: _sass
