---
title: Digidem Lab
timezone: UTC
collections:
  crew:
    title: Crew
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: projects
  values:
    layout: project
    lang: sv
- scope:
    path: ''
    type: crew
  values:
    lang: sv
email: petter@p-jo.se
contact:
  sv:
    title: Prata med oss!
    text: Digidem Lab är en ideell organisation som arbetar med att främja deltagande
      demokrati på alla nivåer i samhället. Vi hjälper gärna er organisation, kommun
      eller parti att hitta nya sätt att engagera och skapa processer för deltagande.
  en:
    title: Get in touch!
    text: Digidem Lab is a non-profit organisation promoting participatory democracy
      on all levels of society. Get in touch to see how we can help your movement
      or organisation to find new processes and tools for participation.
questions:
  sv: Frågor? Prata med oss!
  en: Questions? Get in touch!
baseurl: 
url: http://digidemlab.org
author: Digidem Lab
twitter:
  username: digidemlab
facebook:
  publisher: digidemlab
logo: "/assets/logotyp.png"
social:
  links:
  - https://twitter.com/digidemlab
  - https://www.facebook.com/digidemlab
  - https://www.instagram.com/digidemlab/
  - https://github.com/benbalter
github_username: p-jo
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components
- path
theme: minima
sass:
  sass_dir: _sass
gems:
- jemoji
- jekyll-seo-tag
