---
title: Digidem Lab v2
timezone: UTC
collections:
  crew:
    title: Crew
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
    type: pages
  values:
    layout: page
email: petter@p-jo.se
description: Digidem Lab skapar framtidens processer för demokratiskt deltagande.
  Vi sätter nya verktyg för kollektiv intelligens i dina händer.
contact-title: Få tag på oss!
contact-text: Digidem Lab är en ideell organisation som arbetar med att främja deltagande
  demokrati på alla nivåer i samhället. Vi hjälper gärna er organisation, kommun eller
  parti att hitta nya sätt att engagera och skapa processer för deltagande.
baseurl: "/digidemlab-v2"
url: 
author: Digidem Lab
twitter_username: digidemlab
github_username: p-jo
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components
- path
theme: minima
sass:
  sass_dir: _sass
gems:
- jemoji
